/**
 * This file was generated via `supabase gen types typescript --linked`.
 * Do not edit this file manually.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      alert_events: {
        Row: {
          action: string;
          alert_id: string;
          created_at: string;
          id: string;
          metadata: Json;
          user_id: string | null;
        };
        Insert: {
          action: string;
          alert_id: string;
          created_at?: string;
          id?: string;
          metadata?: Json;
          user_id?: string | null;
        };
        Update: {
          action?: string;
          alert_id?: string;
          created_at?: string;
          id?: string;
          metadata?: Json;
          user_id?: string | null;
        };
        Relationships: [];
      };
      bankroll_accounts: {
        Row: {
          created_at: string;
          currency: string;
          current_balance: number;
          id: string;
          label: string;
          starting_balance: number;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          created_at?: string;
          currency: string;
          current_balance?: number;
          id?: string;
          label: string;
          starting_balance: number;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          created_at?: string;
          currency?: string;
          current_balance?: number;
          id?: string;
          label?: string;
          starting_balance?: number;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [];
      };
      bet_tags: {
        Row: {
          bet_id: string;
          tag: string;
          tagged_at: string;
        };
        Insert: {
          bet_id: string;
          tag: string;
          tagged_at?: string;
        };
        Update: {
          bet_id?: string;
          tag?: string;
          tagged_at?: string;
        };
        Relationships: [];
      };
      bets: {
        Row: {
          american_odds: number | null;
          bankroll_id: string | null;
          created_at: string;
          decimal_odds: number | null;
          event_name: string;
          expected_value: number | null;
          id: string;
          market: string;
          notes: string | null;
          placed_at: string;
          settled_at: string | null;
          settled_payout: number | null;
          status: Database["public"]["Enums"]["bet_status"];
          updated_at: string;
          user_id: string;
          wager_amount: number;
        };
        Insert: {
          american_odds?: number | null;
          bankroll_id?: string | null;
          created_at?: string;
          decimal_odds?: number | null;
          event_name: string;
          expected_value?: number | null;
          id?: string;
          market: string;
          notes?: string | null;
          placed_at?: string;
          settled_at?: string | null;
          settled_payout?: number | null;
          status?: Database["public"]["Enums"]["bet_status"];
          updated_at?: string;
          user_id: string;
          wager_amount: number;
        };
        Update: {
          american_odds?: number | null;
          bankroll_id?: string | null;
          created_at?: string;
          decimal_odds?: number | null;
          event_name?: string;
          expected_value?: number | null;
          id?: string;
          market?: string;
          notes?: string | null;
          placed_at?: string;
          settled_at?: string | null;
          settled_payout?: number | null;
          status?: Database["public"]["Enums"]["bet_status"];
          updated_at?: string;
          user_id?: string;
          wager_amount?: number;
        };
        Relationships: [];
      };
      creator_posts: {
        Row: {
          content: string;
          creator_id: string;
          id: string;
          market: string | null;
          metadata: Json | null;
          published_at: string;
          title: string;
        };
        Insert: {
          content: string;
          creator_id: string;
          id?: string;
          market?: string | null;
          metadata?: Json | null;
          published_at?: string;
          title: string;
        };
        Update: {
          content?: string;
          creator_id?: string;
          id?: string;
          market?: string | null;
          metadata?: Json | null;
          published_at?: string;
          title?: string;
        };
        Relationships: [];
      };
      creator_profiles: {
        Row: {
          avatar_url: string | null;
          bio: string | null;
          created_at: string;
          display_name: string;
          handle: string;
          id: string;
          specialties: string[] | null;
        };
        Insert: {
          avatar_url?: string | null;
          bio?: string | null;
          created_at?: string;
          display_name: string;
          handle: string;
          id?: string;
          specialties?: string[] | null;
        };
        Update: {
          avatar_url?: string | null;
          bio?: string | null;
          created_at?: string;
          display_name?: string;
          handle?: string;
          id?: string;
          specialties?: string[] | null;
        };
        Relationships: [];
      };
      creator_subscriptions: {
        Row: {
          created_at: string;
          creator_id: string;
          id: string;
          status: string;
          user_id: string;
        };
        Insert: {
          created_at?: string;
          creator_id: string;
          id?: string;
          status?: string;
          user_id: string;
        };
        Update: {
          created_at?: string;
          creator_id?: string;
          id?: string;
          status?: string;
          user_id?: string;
        };
        Relationships: [];
      };
      edge_alerts: {
        Row: {
          created_at: string;
          edge_value: number;
          id: string;
          market: string;
          message: string;
          origin: Database["public"]["Enums"]["alert_origin"];
          resolved_at: string | null;
          source_handle: string | null;
          sportsbook: string | null;
          status: string;
          trigger_threshold: number | null;
          triggered_at: string;
          user_id: string | null;
        };
        Insert: {
          created_at?: string;
          edge_value: number;
          id?: string;
          market: string;
          message: string;
          origin: Database["public"]["Enums"]["alert_origin"];
          resolved_at?: string | null;
          source_handle?: string | null;
          sportsbook?: string | null;
          status?: string;
          trigger_threshold?: number | null;
          triggered_at?: string;
          user_id?: string | null;
        };
        Update: {
          created_at?: string;
          edge_value?: number;
          id?: string;
          market?: string;
          message?: string;
          origin?: Database["public"]["Enums"]["alert_origin"];
          resolved_at?: string | null;
          source_handle?: string | null;
          sportsbook?: string | null;
          status?: string;
          trigger_threshold?: number | null;
          triggered_at?: string;
          user_id?: string | null;
        };
        Relationships: [];
      };
      user_profiles: {
        Row: {
          auth_user_id: string;
          bankroll_goal: number | null;
          created_at: string;
          favorite_sports: string[] | null;
          id: string;
          preferred_timezone: string | null;
          updated_at: string;
        };
        Insert: {
          auth_user_id: string;
          bankroll_goal?: number | null;
          created_at?: string;
          favorite_sports?: string[] | null;
          id?: string;
          preferred_timezone?: string | null;
          updated_at?: string;
        };
        Update: {
          auth_user_id?: string;
          bankroll_goal?: number | null;
          created_at?: string;
          favorite_sports?: string[] | null;
          id?: string;
          preferred_timezone?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      alert_origin: "model" | "creator" | "manual";
      bet_status: "pending" | "won" | "lost" | "push" | "void";
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

export type AlertEvent = Database["public"]["Tables"]["alert_events"]["Row"];
export type AlertOrigin = Database["public"]["Enums"]["alert_origin"];
export type BankrollAccount = Database["public"]["Tables"]["bankroll_accounts"]["Row"];
export type Bet = Database["public"]["Tables"]["bets"]["Row"];
export type BetStatus = Database["public"]["Enums"]["bet_status"];
export type CreatorPost = Database["public"]["Tables"]["creator_posts"]["Row"];
export type CreatorProfile = Database["public"]["Tables"]["creator_profiles"]["Row"];
export type CreatorSubscription = Database["public"]["Tables"]["creator_subscriptions"]["Row"];
export type EdgeAlert = Database["public"]["Tables"]["edge_alerts"]["Row"];
export type UserProfile = Database["public"]["Tables"]["user_profiles"]["Row"];
