import { NextResponse } from "next/server";

import { fetchSportsData, type SportsQuery } from "@/lib/sports-data";

type PlannedToolCall<TName extends string, TArgs> = {
  toolName: TName;
  args: TArgs;
};

type FetchSportsArgs = Omit<SportsQuery, "query">;

type ChatRequestBody = {
  /** Complete prompt entered by the user. */
  prompt: string;
  /**
   * List of tool calls generated by the planner. For this mock implementation
   * we only expect a single call to the fetchSportsData tool.
   */
  plannedToolCalls?: PlannedToolCall<"fetchSportsData", FetchSportsArgs>[];
};

type ChatResponseBody = {
  result: Awaited<ReturnType<typeof fetchSportsData>>;
};

export async function POST(request: Request) {
  const { prompt, plannedToolCalls = [] }: ChatRequestBody = await request.json();

  const [toolCall] = plannedToolCalls;
  if (!toolCall) {
    return NextResponse.json(
      { error: "Expected a planned call to fetchSportsData." },
      { status: 400 },
    );
  }

  const result = await fetchSportsData({
    ...toolCall.args,
    query: prompt,
  });

  const payload: ChatResponseBody = { result };
  return NextResponse.json(payload);
}
